#include <iostream>
#include <stdio.h>
#include <fstream>
#include <curl/curl.h>
#include <gtk-3.0/gtk/gtk.h>
#include <gtk/gtk.h>
#include <gtk-3.0/gdk/gdk.h>
#include <gdk/gdk.h>
#include <webkit2/webkit2.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL.h>
#include "curly.h"
#include <vector>
#include <sstream>
#include <string>
#include <unistd.h> 
#include <thread>
#include <atomic>